### PR TITLE
fix env var typo in curl command

### PR DESCRIPTION
**Pull request by wahlfeld**

### CODE REVIEW

**Comment by petervandenabeele** [comment]
I think the original `${ENV_VARIABLE}` interpolation is correct and the proposed change in this Merge Request is not needed (and not even correct).

**Comment by wahlfeld** [comment]
Well, regardless, the original format doesn't work for me and the proposed change does. I don't think there's anything special/unique about my setup. Also looking at the open issues I'm not the only one who experienced the issue either.

**Comment by bryantbiggs** [comment]
the way it is written is correct, this PR technically incorrect; what you are changing this to is technically [brace expansion](https://ss64.com/bash/syntax-expand.html). Environment variables on there own are typically just `$FOO` but when inserted into a string its better to wrap with curly brackets to distinguish the exact variable name like `${FOO}BAR`

**Comment by kelseyhightower** [comment]
I've tested this in the update on master and based on my results I'm keeping the original syntax in use.

**Pull request closed without merging**
