### PR TITLE
add commands for windows client users

### PR DESCRIPTION
**Pull request by stubblyhead**
I was disappointed to see several labs in that this tutorial didn't have any instructions for Windows users, leaving them to type a lot of commands longhand (or at least greatly increase the amount of copy/pasting). 
I wrote some Powershell to bridge that gap, I hope you find it useful.

### CODE REVIEW

**Comment by zatricky** [comment]
If it were my choice, I'd be of two minds. I see the merit - but this also would diverge from the guide's distilled nature.

The parts re compatibility could possibly be merged anyway.

Assuming KH doesn't want to merge all the Windows commands, then perhaps some guidance on the replacement commands or download URLs would be a good halfway point.

Another possibility for Windows users is instead to suggest installing the Ubuntu/Windows Subsystem feature.

**Comment by tokiwinter** [comment]
I was always under the impression that with things like this, KH would advise "fork, modify, and be merry", essentially. imho this is going to clog up the guide for what is probably going to benefit a very small minority of the targeted user base.

**Comment by tomfotherby** [comment]
Whilst I appreciate the work done, I concur with @tokiwinter - perhaps Windows users could maintain their own **fork**. Whilst you are at it, could someone do a fork for `aws` users too? ;) (i.e. you can't please everyone)

**Comment by stubblyhead** [comment]
> Whilst you are at it, could someone do a fork for aws users too? ;) (i.e. you can't please everyone)

Actually... https://github.com/kelseyhightower/kubernetes-the-hard-way/tree/1.4

**Comment by kelseyhightower** [comment]
This is a great PR, but as others have stated I don't have the bandwidth to test on windows. I run through each command multiple times to ensure everything works. Adding windows would increase the time it takes for me to maintain this guide. Please fork, and keep a windows port up to date. I tag each "release" of this guide to make it easier to keep up.

**Pull request closed without merging**
