### PR TITLE
Replace `jq` with `--query` param in AWS commands.

### PR DESCRIPTION
**Pull request by steeef**
I figured a PR was worth more than a Twitter reply. Look ok?

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@steeef I need to run through the whole thing with these changes in place, if it works, then yeah we should do it.

Thanks for the PR.

**Comment by steeef** [comment]
To be honest, I haven't run these commands myself. However, I'm so enmeshed in AWS Land with $currentjob that I'm confident these should work. Barring stupid typos, obviously. I'll give it a shot and test them too, though. Gives me an excuse to try out Kubernetes :). Thanks for this, btw. These are the kind of tutorials that really make the concepts stick for me.

**Comment by steeef** [comment]
Took me a few tries to get it right, but I got through the whole tutorial with these changes. Works!

**Comment by tsupertramp** [comment]
I did it the same way used -query instead of jq - This is the old doc before linking to yours https://github.com/ivx/kubernetes-the-hard-way-aws/blob/3e9d08e7b955aff423669f8a64e4ba31827b5b20/docs/01-infrastructure.md

Greetings Thomas :)

**Comment by tsupertramp** [comment]
First of all - Thanks for porting your documentation to aws.

I used the query parameter as well for my mirror documentation (which i deleted after you added your version).

This commit shows how i used the query filter to create infrastructure:

https://github.com/ivx/kubernetes-the-hard-way-aws/blob/3e9d08e7b955aff423669f8a64e4ba31827b5b20/docs/01-infrastructure.md

As well there are some tricks to get easy ssh access to instances without using ip addresses. After seeing your first version i would like to switch to gce instantly - Just because of command line tool.

Maybe it convinces you to merge the pull request :)

Greetings, Thomas

**Comment by steeef** [comment]
@tsupertramp looks good, thanks! RE: simplifying the ssh commands: it kind of subverts the purpose of this tutorial, since you're skipping some manual steps that might be useful to learn.

**Comment by kelseyhightower** [comment]
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.

**Pull request closed without merging**
